
services:
  bot:
    image: vulps23/project-timezone:latest
    container_name: timey-zoney-bot-container
    volumes:
      - timezone-data:/app/database
    env_file:
      - ./.env
    
    # Restart policy
    restart: unless-stopped

# Named volume for database persistence
volumes:
  timezone-data:
    driver: local
